server:
  port: 8081
spring:
  datasource: # 配置数据库
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test   #数据库名
    type: com.alibaba.druid.pool.DruidDataSource
